spring.application.name=SpringJpaDemo

# In-memory database
spring.datasource.url=jdbc:h2:file:./data/mydb;AUTO_SERVER=TRUE
#spring.datasource.url=jdbc:h2:mem:testdb

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
